### ISSUE TITLE
Make REPL embeddable

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/v2.svelte.dev#107]
Like jsfiddle — would be cool if you could embed the REPL output, or maybe a tabbed view showing component and JSON as well

**Comment by Ryuno-Ki** [comment]
I like, how [CodePen does it](https://blog.codepen.io/documentation/features/embedded-pens/).

**Comment by fskreuz** [comment]
@evs-chris created https://github.com/ractivejs/playground for Ractive which runs all the demos and tutorials on some areas  of site (look for code blocks with a "Run It"). More inline than embedded though.
