### ISSUE TITLE
REPL: Watching for data changes is flaky

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/v2.svelte.dev#202]
Inspired by https://github.com/sveltejs/svelte/issues/1068 but that's not the only issue. If you pop open the console and run `app.set({foo:'bar'})` where `foo` is some as-yet unknown data property, the data section of the REPL does not update. *Probably* the easiest solution would be to monkey patch the compiled component's internal `_set` method so that we can watch for any changes to any fields, or even the addition of new fields. But that's ugly and definitely not a best practice type of thing.

(As an aside, what was the rationale for not providing an official way to watch for that? Was it merely to save bytes in compiled components, or was it because doing so was something that component authors or consumers shouldn't do?)

**Comment by Conduitry** [comment]
Submitted #203 for the important part of this. The other part (about watching for brand-new data properties being added) can wait for another time.

**Comment by Rich-Harris** [comment]
Redeployed with #203 (thanks) but I guess we can leave this open in case we're ever inspired to tackle the second part

**Comment by Rich-Harris** [comment]
One downside of the new approach: we get all the `computed` properties in the lower right, which is undesirable

**Comment by Conduitry** [comment]
The SVG clock example is also currently broken (not positive that that started happening with this change). It looks like the `time` value gets serialized as a plain string into the properties, and then gets unserialized (as a string) and isn't actually a `Date`.

**Comment by Rich-Harris** [comment]
I think that *is* related to this change. I think we might need to revert it and come at it from a different angle :(
