### ISSUE TITLE
Svelte/Sapper Visual Identity

### ISSUE THREAD

**Issue by simonlayfield** [sveltejs/v2.svelte.dev#335]
I've set this issue up to track the conversation around the visual elements of Svelte and Sapper, in particular the logos and any proposed visual improvements to their documentation sites.

There's already been a thread concerning the tagline of Sapper https://github.com/sveltejs/sapper/issues/263 which we can factor in.

Feel free to make suggestions, textual or graphic, but let's try and keep a concerted effort not to stray too far from what already exists. Our approach should be evolutionary not revolutionary!

I'll kick things off with a couple of loose ideas.

![svelte-branding-concept-001](https://user-images.githubusercontent.com/2576361/43139454-17e77356-8f95-11e8-9ce4-19239c690d08.jpg)
<img width="972" alt="screen shot 2018-07-24 at 10 40 04 pm" src="https://user-images.githubusercontent.com/2576361/43139348-d68bb96c-8f94-11e8-98f3-b561f870f6f1.png">
<img width="959" alt="screen shot 2018-07-24 at 10 45 44 pm" src="https://user-images.githubusercontent.com/2576361/43139349-d6bdf3dc-8f94-11e8-8936-758bcb6a27e9.png">

**Comment by Rich-Harris** [comment]
Thanks so much @simonlayfield!

I like the idea of having these fairly abstract logos, they would work nicely as favicons/twitter avatars and the like. Of the two Svelte logos I prefer the second one — the first one is possibly a little too subtle :) 

In terms of layout, my natural instinct is to align the logo with the name so that it's not poking out by itself, like this...

![svelte-homepage](https://user-images.githubusercontent.com/1162160/43146188-b7723ba2-8f2e-11e8-80b3-53f2613ce974.png)

...but maybe that's just me being unimaginative?

What sort of things did you anticipate having in the grey box? Presumably it would be best if it was something visual (i.e. not more text like 'recent blog posts' or whatever) — maybe a video introduction, or a slimmed-down REPL.

That is a *much* nicer shade of green. I'm tempted to go and change that right away...

**Comment by tomcon** [comment]
If the svelte logo could give the actual impression of speed then that'd be very good imo: 
e.g. examples only! not actual images to use
![speed1](https://user-images.githubusercontent.com/647145/43146228-b557ffbc-8f58-11e8-92c2-ff28a2681be2.png)
![speed2](https://user-images.githubusercontent.com/647145/43146238-b9a84c98-8f58-11e8-8da9-4e48e721ea48.jpg)

**Comment by tomcon** [comment]
The second logo by Simon has already a bit of that going on, just needs polishing up and making even more "speedy"

**Comment by arxpoetica** [comment]
Potential gray box content: actual embedded REPL content/examples. So, maybe a carousel or tabbed group with 6 or more examples?

**Comment by arxpoetica** [comment]
Also, I like the idea of speed in the logo design. I also like the idea of somehow visually showing the "disappearing framework" parts coming together to make a whole idea. Which that second design somewhat conveys.

**Comment by simonlayfield** [comment]
@Rich-Harris I reckon you're spot on with that idea. The logo form to the side also tends to work better in mastheads/headers etc, and generally be easier to align to other elements. Good thinkin'.

The grey box was just a visual placeholder. I havent put any real thought in to the layout of the homepages just yet - the reason I've displayed them this way is that I like to give some context when posting logo ideas because I find it helps see it roughly in situ. BUT one thing I used to like about the Ractive homepage was that you had a live example to tinker with, so the REPL idea like @arxpoetica suggests is pretty neat.

That being said, I think that visually presenting the benefits of Svelte using some cool little diagrams could be an idea too. Perhaps a graphic to represent each of the three points mentioned in the text beneath the logo?

@tomcon Yeah, I have a couple of ideas of how I might more obviously tie in the idea of speed with the second idea. I'll have a play and see how it goes.

@arxpoetica Actually, the 'speed' tie in is coincidental. Originally I was trying to make half of the circle appear as if it was partially disappearing (the magical disappearing UI framework). Either way it works!

**Comment by simonlayfield** [comment]
Yeeesh. I've been nudging this concept around for a week or so and just going round in circles with it.

Something about it doesn't feel on the money. It's the rough concept as shown originally just developed a bit further, with the 'speed' perhaps better represented by the staggered lines?

<img width="479" alt="svelte-concept-rework" src="https://user-images.githubusercontent.com/2576361/43522306-5508d2be-95dc-11e8-854f-8d2868dd907c.png">

In the interests of moving things along I'll post it and then have a think about where to go from here.

**Comment by arxpoetica** [comment]
What if we did this with it?

![image](https://user-images.githubusercontent.com/111424/43537373-5fa28bee-957c-11e8-86d6-c6c4573b6d77.png)

```</😆>```

For reals though, I like it.

**Comment by simonlayfield** [comment]
Needs more horses. And more flames. But sure I'm cool with it.

As I said, I feel like there's something not quite there with it, but I might draw a line under this one and move on to another idea.

**Comment by simonlayfield** [comment]
More tweaks.

![svelte-branding-concept-003](https://user-images.githubusercontent.com/2576361/43833225-6c81fa8a-9b4d-11e8-8a97-e2efb8508589.jpg)

I think this is actually an improvement in some ways BUT does move away from the solid circle shape a bit. In my original whipped together concept above both Svelte and Sapper share branding characteristics to appear as related projects.

It's also taking more of a literal form (a meteor, perhaps, and yeah I'm aware of Meteor JS) and originally I was trying to keep things on the abstract side.

Just my thoughts. I might be overthinking it.

Feel free to share yours.

**Comment by arxpoetica** [comment]
Also looks like a hand.

**Comment by simonlayfield** [comment]
@arxpoetica this is true.

**Comment by simonlayfield** [comment]
Ok so, moving on. Back to simple shapes.

![svelte-branding-concept-004](https://user-images.githubusercontent.com/2576361/44029428-a1eb7722-9f40-11e8-9d9e-849f76d5a2c8.jpg)

This was a progression of two lines creating an S shape in the negative space, which I didn't think had enough impact so I connected the lines.

Thoughts?

**Comment by simonlayfield** [comment]
Further developments.

![svelte-branding-concept-005](https://user-images.githubusercontent.com/2576361/44030999-e8f38150-9f45-11e8-9c15-eaf52cf84053.jpg)

So, I think as far as form goes this is pretty tidy.

It's an S and also a bolt-like shape so I think this conveys speed quite well. Happy to hear feedback though!

**Comment by Rich-Harris** [comment]
Oh man that last one is awesome! When I saw the one right before, it made me think of lightning — I even fired up Illustrator to try and show what was in my head but predictably it looks garbage next to that one. I vote for it. I also really like the idea of Svelte and Sapper both having circular logos — it works well in avatars, and can be extended to any future sibling projects we dream up.

I had to at least *try* to see what a flaming horse logo would look like:

![artboard 1 copy](https://user-images.githubusercontent.com/1162160/44031979-b5cc5cce-9ed3-11e8-9ab5-3ce5d81023a0.png)

(You may recognise the horse in question.)

![image](https://user-images.githubusercontent.com/1162160/44032007-cb2ee244-9ed3-11e8-9fe1-e9d616558e92.png)

**Comment by arxpoetica** [comment]
LOL

I'm with Rich; that last one looks fantastic.

**Comment by simonlayfield** [comment]
There's been a bit of a speedbump, potentially.

A comment was made on the Discord channel that the above concept (or part of it) bears a notable resemblance to an Armanen rune, which in itself isn't bad, but was used to represent 'Schutzstaffel' - an organisation under the Nazi party during WW2.

https://en.m.wikipedia.org/wiki/Schutzstaffel

https://i.pinimg.com/564x/51/55/5f/51555fa4e4e947d03b3f17d0551a94f5.jpg

I have mixed feelings on this, but ultimately don't feel as though I'm in a particularly good position to judge on my own whether the degree of similarity may offend, so look to the good people of Svelte to let me know what they think.

I have a few hours free tonight so will try to tweak it enough that the resemblance is perhaps even less noticeable.

Let me know thoughts.

**Comment by simonlayfield** [comment]
Ok so I've added some variation to the width of the bolt shape.

<img width="566" alt="screen shot 2018-08-15 at 12 13 48 am" src="https://user-images.githubusercontent.com/2576361/44097216-9f921126-a020-11e8-8f09-2f642040a72e.png">

To be honest if anything I think this makes it look even closer - so....

I don't know. I'm stuck now.

**Comment by arxpoetica** [comment]
I think the sensitivity is important, but (my take), in this case there's enough dissimilarity to not worry about it at all.

Just do a search for lightning bolt on Google and you'll see it's *really* not an issue: https://www.google.com/search?q=lightning+bolt+logos&pws=0&gl=us&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi31LftuO_cAhVk74MKHYPCBYUQ_AUICigB&biw=1440&bih=803

Again, my take.

**Comment by Rich-Harris** [comment]
I think the fact that it's meant to represent 'S' for 'Svelte' makes it *slightly* more treacherous. One thing we could consider — don't know if this is a good idea, just throwing it out there — is going for a diamond shape instead of a circle to increase the dissimilarity. 

![artboard 1 0 5x](https://user-images.githubusercontent.com/1162160/44179326-4d8e3680-a0c4-11e8-8af5-c23f0223088b.png)

![artboard 1 copy 0 5x](https://user-images.githubusercontent.com/1162160/44179329-4f57fa00-a0c4-11e8-89cd-4bf37a6bf74d.png)

![artboard 1 copy 2 0 5x](https://user-images.githubusercontent.com/1162160/44179335-53841780-a0c4-11e8-8a1d-f4d39c44c33e.png)

**Comment by Rich-Harris** [comment]
2001 is a good association to have! Shame the monolith doesn't lend itself too well to a logo.

![image](https://user-images.githubusercontent.com/1162160/44267407-11f68800-a1fc-11e8-90f1-1dd8a8a39f49.png)

We could do HAL... not sure it's recognisable enough though.

![artboard 1 copy 3 0 5x](https://user-images.githubusercontent.com/1162160/44267488-68fc5d00-a1fc-11e8-893d-9cd9089a9b92.png)

For real though, what if we *did* do a horse with a mane of fire? It's playful, unique, and it has a horse (no animal better represents the word 'svelte' — they conjure associations of strength, speed, beauty, independence etc). This is the best my Illustrator skills (plus the [noun](https://thenounproject.com/iconsproducer/collection/horse-face/?i=1324977) [project](https://thenounproject.com/term/fire/347371/)) will permit, but you get the idea...

![artboard 1 copy 0 5x](https://user-images.githubusercontent.com/1162160/44267587-d7411f80-a1fc-11e8-8ebb-1f847d158113.png)

![artboard 1 copy 2 0 5x](https://user-images.githubusercontent.com/1162160/44267800-8bdb4100-a1fd-11e8-886d-0bcb6c4c279f.png)

Simon is probably cringing by now so I'll shut up for a while.

**Comment by arxpoetica** [comment]
Ha ha ha love the horse.

**Comment by tomcon** [comment]
![image](https://user-images.githubusercontent.com/647145/44308189-62aae400-a3a8-11e8-974d-b8df6274d114.png)

**Comment by silentworks** [comment]
I also like this one, but think if it was something more like what @Rich-Harris mentioned right below it.

https://github.com/sveltejs/svelte.technology/issues/335#issuecomment-412888151

**Comment by Rich-Harris** [comment]
Ha, I can't unsee the Opel thing now! Even if it is flipped vertically. @tomcon I think if we can have a single-colour logomark it's better — it's more adaptable to different forms, and means that you can have *the* Svelte colour and *the* Sapper colour etc.

**Comment by simonlayfield** [comment]
Tonight I have been mostly praying to the design gods.

![svelte-branding-concept-007](https://user-images.githubusercontent.com/2576361/44338651-e278a180-a4c1-11e8-8c15-871032fa692d.jpg)

@Rich-Harris Me and my mouth. I shouldn't have mentioned it!

On that point, though, I will say that it's not uncommon for logos to have similarities. I realise we want something that looks super rad and fit with what svelte is about (I totally do too), but the chances are whatever we decide on will bear a notable resemblance to some other logo, somewhere.

![brands](https://user-images.githubusercontent.com/2576361/44339435-aeeb4680-a4c4-11e8-9d0e-83cacfd7f733.jpg)

This isn't me saying I don't care - just to keep expectations realistic.

**Comment by Conduitry** [comment]
Those prayers paid off imo! That last one looks great and doesn't make me think of Nazis even a little!

**Comment by arxpoetica** [comment]
Totally sold on that last one.

**Comment by arxpoetica** [comment]
Forgive me for free-wheeling with your rubric, I sorta couldn't help myself.

![image](https://user-images.githubusercontent.com/111424/44367301-98c19400-a48c-11e8-8ab6-9713a52c206b.png)

For the record, I like yours more. ;)

**Comment by arxpoetica** [comment]
More doodling. :P

![image](https://user-images.githubusercontent.com/111424/44367626-93187e00-a48d-11e8-9115-ab3dfc8e6d6a.png)

**Comment by arxpoetica** [comment]
More doodling. 😜

![image](https://user-images.githubusercontent.com/111424/44367744-dbd03700-a48d-11e8-82b9-767a5f5488f5.png)

**Comment by Rich-Harris** [comment]
I've been doing some doodling as well 😀 https://svelte.technology/repl?version=2.11.0&gist=053b7cc58c62ceddeeeee65cc2a5f33e

**Comment by arxpoetica** [comment]
Hot cannons that is awesome @Rich-Harris!

I like subtle, so here's my take: https://svelte.technology/repl?version=2.11.0&gist=da7a7575b9c571827e644329a3dcc65b

**Comment by simonlayfield** [comment]
Soooooo....I was digging around on Bitbucket this afternoon minding my own business when BAM!

![screen shot 2018-08-21 at 12 10 56 pm](https://user-images.githubusercontent.com/2576361/44376389-abdf6d00-a53b-11e8-88cb-d0908d99a533.png)

That didn't take long.

**Comment by silentworks** [comment]
@simonlayfield I personally don't think it looks anything like what you have created.

**Comment by Rich-Harris** [comment]
Yeah, I think we're in a good place — the logo is fresh, unique and works well for the project. I say we go with it.

@simonlayfield fantastic work — are you able to share an .ai or .svg or did you have more things in mind?

**Comment by simonlayfield** [comment]
@arxpoetica Cool! I like the last one of [this group](https://github.com/sveltejs/svelte.technology/issues/335#issuecomment-414467206)

@silentworks Fair enough. I've been looking at lightning bolts for too long, clearly!

Those animations. Lawdy. Very cool.

@Rich-Harris Sure, ok. Provided Yeah happy to provide an svg that's easy enough.

Am I 100% happy with it? It's probably more like 80%, but I think it's a solid option and provided the general community opinion is the same then that's a good place to be.

I think it's probably a slight improvement not to rotate it so much. Maybe this is better:

![svelte-branding-concept-008](https://user-images.githubusercontent.com/2576361/44403338-85e7b600-a597-11e8-946d-0c77517dddda.jpg)

That way the bottom looks more flush with the typeface (it isn't precisely, but you get what I mean)

<img width="586" alt="screen shot 2018-08-21 at 11 14 17 pm" src="https://user-images.githubusercontent.com/2576361/44403504-fa225980-a597-11e8-86cb-ff5c3f5a3840.png">

**Comment by simonlayfield** [comment]
As far as next steps go, should we focus on the Svelte doc site (homepage mostly), close off Svelte completely and then move on to Sapper?

**Comment by arxpoetica** [comment]
Totally think the correct tipping degree took that logo from 10 to 11. Awesome work.

**Comment by Rich-Harris** [comment]
> As far as next steps go, should we focus on the Svelte doc site (homepage mostly), close off Svelte completely and then move on to Sapper?

Sounds like a good idea, yeah. Let's do that

**Comment by Rich-Harris** [comment]
(@arxpoetica did you mean to close the issue? reopening in case you just fat-fingered the button 😀 )

**Comment by tomcon** [comment]
Re. tagline - @fusionstrings came up with something promising here:  https://github.com/sveltejs/sapper/issues/263#issuecomment-415005442

> Sapper
> All weather apps. Boot quickly build rapidly

Trying to keep to the Sapper theme, how about:
Build rapidly Boot quickly Get the job done

**Comment by antony** [comment]
As I learned from the neverending rebranding of BSkyB's NowTV back in the day, the correct name for the "tipping" is "cheekiness". The right cheeky slant can make or break a logo :rofl: 

In all seriousness, love the new logo. See you all at the next rebrand.

**Comment by arxpoetica** [comment]
@vedam, those are some amazing contributions. I could see either logo  (yours and @simonlayfield's) working...honestly I'd be hard pressed to pick a favorite, they both have saliency. I really like the clear idea of "links," i.e., Svelte is more than just it's links/parts.

I think I like the first color scheme in 1.1 a bit more. Orange-y, and green.

Awesome work.

**Comment by vedam** [comment]
> Svelte is more than just it's links/parts

Yeah. Sapper too.
Nice to see that an idea works even without explaination.  ;-)
Thx

**Comment by simonlayfield** [comment]
@vedam This is some great work - hats off to you!

The icon you've put together is really strong and is highly memorable/recognisable which I think is a really great achievement there. The assets around the brand you've created are also clean and distinct. Really nice work.

I would say that one of the challenges  I set out to solve was to create slightly different brand identities for both Svelte and Sapper - even if very similar - because to anyone that doesn't know they're related will see the logos as the same and perhaps be confused. Colour alone doesn't really give you enough distinction between the two, I don't think. On top of that I don't think it's a good idea to only rely on colour as the only difference because at some point the logos may need to be shown in monochrome (i.e. alongside each other, black on white) in which case you lose the distinction between the two.

Needless to say this was a pretty big challenge, and I found myself constantly juggling both Svelte and Sapper concepts to make sure they both looked good independently, but also together.

![svelte-branding-concept-009](https://user-images.githubusercontent.com/2576361/45631975-1ed4f880-ba94-11e8-985c-40fd16f5b7a4.jpg)

^ Here, for example, the Svelte icon shows an abstract 'S' and the same lines are reconfigured for Sapper to show a wing (ties in with it's military meaning and also I guess represents a production state - in flight?).

Anyway - the work you've done is awesome and stylistically a cut above my contributions IMO. Really appreciate you getting involved and putting so much time in!

**Comment by vedam** [comment]
@simonlayfield  thx a lot for your opinion.

I was really afraid that this proposal could be interpreted negatively or arrogant, because I basically arrive after decisions have already been made, lots of work had to be done, and countless designer-emotions have been incorporated.

So I'm very grateful for your constructive and factual analysis.



>I would say that one of the challenges I set out to solve was to create slightly different brand identities for both Svelte and Sapper ...



I absolutely agree with you on this point, and I stumbled upon this question more than one time during the development process.

**But,**
without talking to anyone of the creators **( A )**, I interpreted the current state of the two Products as coupled (At least the Sapper-Part).
Even if Svelte can be used completely independent, so at least Sapper, according to his description, yet has a close connection to svelte. Also in both menus a direct link to each other can be found, so for me as a user, I will definitely realize sooner or later that one might have something to do with the other, and understand the connection/link between the two.

This leads me to the combined **S** which both can use.

If I missinterpreted this point completely, then we maybe should think about different Logos.
If not completely wrong, the combined Logo is a chance of visualizing the advantage the both have if used together. (UMPF describing thoughts in german is easier  ;D)



some point the logos may need to be shown in monochrome (i.e. alongside each other, black on white) in which case you lose the distinction between the two



On this point I cannot agree really (In a print-media disscussion I would allways do)

1. I have no idea what a side-by-side monochrome usecase could be, because we're on the web?
   And if, is this rare case enough to cancel the whole Look-and-feel?
2. Beside their color, the two are differenciated by their Logotype as shown.
   

Overall, you're right. The creators have to decide how strong or loose the separation/relationship has to be visualized and if I met. Showing before asking was my motto in this special case.
With clients at the table I allways ask first.


I hope this all halfway understandable.
And again
**thx for your reply**
Achim

**( A )** How can I explain what I mean by "Identity is more than a Logo", if I'm not visualising what I'm talking of. Words aren't enough in this case, so I decided to follow my interpretation.

**Comment by simonlayfield** [comment]
It's not negative or arrogant at all, you've produced some really nice work.

The two points we've discussed are pretty much coupled together. Personally, I think that two different products with the same logo form has the potential for confusion. It may not be confusing for everyone, but it could be for some. Not everyone will land on the homepage and understand the precise context of the product. Perhaps users land on a documentation page and just see instructions and code. Perhaps people have multiple tabs open and just see a favicon. With two logo forms the same, people either already know that the products are related, or they have to have an intuitive guess, or they have a click around or google it and find out. All but the first scenario are hurdles for the user, which I think can be avoided altogether.

Colour can be used as a point of difference but I think in situations where it's the _only_ point of difference it opens up scenarios where people get confused, and if people with flawless vision are confused, I guarantee those with vision impairment will have an even tougher time. Edge cases they may be, but cases that can be avoided.

I think what you've done is **great**, by the way, and this isn't a critique of the form itself. Perhaps others can provide opinions on whether the potential for confusion is significant.

**Comment by vedam** [comment]
@simonlayfield  great summary.

> Personally, I think that two different products with the same logo form has the potential for confusion

For sure. With two "normal cosumer-products" I would be totally with you and try to avoid this. But from my understanding of these Two special ones, without paying attention to design conventions at first, especially the binding makes them really strong. Maybe I'm completely wrong on this, maybe interpreting too much.

Beside the binding-factor, the color alone doesn't have to do all the differentiation work. On the pages there are always the logotypes (S V E L T E  and S A P P E R) present to make absolutely clear where you have landed.

And as always with corporate design:
There will definitely popup use-cases that will fall on your feet.

In any case...

> Perhaps others can provide opinions on whether the potential for confusion is significant.

... you came up with the ultimate solution and clearification.
Great discussion.

**Comment by vedam** [comment]
> There will definitely popup use-cases that will fall on your feet
Heh. First one is discord:

![discord](https://user-images.githubusercontent.com/64245/45697606-70e64e80-bb66-11e8-9ef9-5694c51a9af4.jpg)

The question is, if the two are really devidable  ;D

**Comment by arxpoetica** [comment]
Just chiming in to say I generally agree with @simonlayfield regarding form, factor, and differentiation. Probably best to have separate-enough logos.

**Comment by Ryuno-Ki** [comment]
Recalling Mozilla's rebranding... I am wondering how the logos would look like on a button / mug / shirt?

For example, if some of the maintainers attend a conference and hand out swags.

**Comment by Ryuno-Ki** [comment]
Plus, would it be worth looking at the used type or is that one set in stone?
(Haven't found any hints on that topic here)

**Comment by vedam** [comment]
@Ryuno-Ki Please have a look at the [proposal](https://github.com/sveltejs/svelte.technology/issues/335#issuecomment-421912789) above.

**Comment by Ryuno-Ki** [comment]
@vedam Okay, found the shirt variant (Superman! :-D)

What about the font? Which font family is used?

**Comment by vedam** [comment]
[Overpass](https://fonts.google.com/specimen/Overpass)
