### ISSUE TITLE
Document how to use with github pages

### ISSUE THREAD

**Issue by aubergene** [sveltejs/v2.svelte.dev#360]
Github pages (and similar) are very popular so it would be good to create a blog post (and perhaps template) for creating a project that can be pushed to github page and add a link to the docs. 

There's examples for Nuxt which are good examples

https://nuxtjs.org/faq/github-pages/

https://hackernoon.com/create-and-publish-a-nuxt-powered-website-on-github-pages-3e922dfa7372

**Comment by pixeline** [comment]
I was actually looking forward to deploying my first SPA with Svelte as a GitHub Pages. I'll see if I can nail an easy method, then publish it as a tutorial on dev.to.

(i discovered Svelte yesterday and it totally grew into my new girlfriend, thanks to the Team for making this jewel ! )

**Comment by pixeline** [comment]
@aubergene Well, here it is! https://dev.to/pixeline/how-to-deploy-a-sapper-pwa-on-github-pages-47lc 

@Conduitry feel free to close this issue if this is enough.

**Comment by Chinyoka1** [comment]
Can you also do it without using sapper?

**Comment by aubergene** [comment]
Great thank you. I didn't know about `gh-pages` very handy. 

@SvenjaJeschke for deploying a plain Svelte app, it's even easier, just replace `'__sapper__/export/yourproject'` with `public`.

**Comment by josecelano** [comment]
I've also created a basic example:

https://github.com/josecelano/svelte-deploy-with-github-actions

It uses GitHub Actions to deploy automatically to GitHub Pages.
