### ISSUE TITLE
Integrating REPLs in the guide

### ISSUE THREAD

**Issue by mindrones** [sveltejs/v2.svelte.dev#383]
Related to #107, there have been talks about integrating the REPLs in the documentation.

As mentioned by @pngwn in #382 this could hit performances if we embed tenths of these in a long guide so maybe an option could be to make a REPL run only after clicking on it.

Related to REPL searchability, we could mark that a certain example is embedded in the official guide.

There should be way to avoid the scroll-trap to avoid what happens on maps embedded in scrollable documents (again maybe after mouse-entering/clicking on it?).

It should be possible to fold/minimize the repl to facilitate reading the text around it in a guide.

**Comment by pngwn** [comment]
Regarding performance, you could just not render the REPL if it isn't in view/ about to come into view. The same could be true of other interactive elements on the page.  This is easier said than done obviously, but it is a possibility.

**Comment by mindrones** [comment]
A possible application (mentioned in the FAQ issue linked above) are how tos: for each use case "How do I ...X" we could show an example in an embedded REPL, so that the user don't have to leave the documentation.
